DECLARE
  pedido_reverso number;
  documento_fiscal_reverso number;
  num_pedido number := :num_pedido;
  num_filial_pedido number := :num_filial_pedido;
BEGIN

SELECT NRO_PEDIDO_REVERSO INTO pedido_reverso FROM MV_PEDIDO_REVERSO WHERE NRO_PEDIDO = num_pedido and FILIAL_PEDIDO = num_filial_pedido and ROWNUM = 1;

IF pedido_reverso IS NOT NULL THEN
  
  FOR T IN (SELECT NRO_PRE_RECIBO_REVERSO FROM MV_PRE_RECIBO_REVERSO WHERE NRO_PEDIDO_REVERSO = pedido_reverso) LOOP
      DELETE MV_CREDITO_REVERSO where nro_pre_recibo_reverso = T.NRO_PRE_RECIBO_REVERSO;
    
      DELETE FROM MV_CONTROLE_FATURAMENTO
      WHERE SEQ_CONTROLE_FATURAMENTO IN(
      SELECT  AP.SEQ_CONTROLE_FATURAMENTO
      FROM MV_APROVACAO_REVERSO AP   
      WHERE AP.NRO_PRE_RECIBO_REVERSO = T.NRO_PRE_RECIBO_REVERSO);
      
      DELETE FROM MV_ITEM_APROVACAO_REVERSO
      WHERE NRO_APROVACAO_REVERSO IN(
      SELECT  AP.NRO_APROVACAO_REVERSO
      FROM MV_APROVACAO_REVERSO AP   
      WHERE AP.NRO_PRE_RECIBO_REVERSO = T.NRO_PRE_RECIBO_REVERSO);
      
      DELETE FROM MV_APROVACAO_REVERSO
      WHERE NRO_PRE_RECIBO_REVERSO = T.NRO_PRE_RECIBO_REVERSO;
      
      DELETE FROM MV_APROVACAO_SERVICO_REVERSO
      WHERE NRO_PRE_RECIBO_REVERSO = T.NRO_PRE_RECIBO_REVERSO;
      
      DELETE FROM MV_PRE_RECIBO_PRODUTO_REVERSO
      WHERE NRO_PRE_RECIBO_REVERSO = T.NRO_PRE_RECIBO_REVERSO;
      
      DELETE FROM MV_PRE_RECIBO_SERVICO_REVERSO
      WHERE NRO_PRE_RECIBO_REVERSO = T.NRO_PRE_RECIBO_REVERSO;
      
      DELETE MV_APROVACAO_PLANILHA_REVERSO 
      WHERE NRO_PRE_RECIBO_REVERSO = T.NRO_PRE_RECIBO_REVERSO;
      
      DELETE MV_PRE_RECIBO_PLANILHA_REVERSO 
      WHERE NRO_PRE_RECIBO_REVERSO = T.NRO_PRE_RECIBO_REVERSO;
      
      DELETE MV_PRE_RECIBO_REVERSO 
      WHERE NRO_PRE_RECIBO_REVERSO = T.NRO_PRE_RECIBO_REVERSO;
  
  END LOOP;
  
  DELETE MV_TEF_REVERSO WHERE NRO_PEDIDO_REVERSO = pedido_reverso;
  
  DELETE MV_PLANILHA_PAGTO_REVERSO WHERE NRO_PEDIDO_REVERSO = pedido_reverso;
  
  SELECT NRO_DOCUMENTO_FISCAL_REVERSO INTO documento_fiscal_reverso from  MV_DOCUMENTO_FISCAL_REVERSO where nro_pedido_reverso = pedido_reverso;
  
  DELETE MV_NF_DOC_FISCAL_REVERSO WHERE NRO_DOCUMENTO_FISCAL_REVERSO = documento_fiscal_reverso;
  
  DELETE MV_ITEM_DOC_FISCAL_REVERSO WHERE NRO_PEDIDO_REVERSO = pedido_reverso;
  
  DELETE MV_DOCUMENTO_FISCAL_REVERSO WHERE NRO_PEDIDO_REVERSO = pedido_reverso;
  
  DELETE MV_PRODUTO_REVERSO WHERE NRO_PEDIDO_REVERSO = pedido_reverso;
  
  DELETE MV_SERVICO_REVERSO WHERE NRO_PEDIDO_REVERSO = pedido_reverso;
  
  DELETE MV_PEDIDO_REVERSO WHERE NRO_PEDIDO_REVERSO = pedido_reverso;
    
  DELETE MV_FILA_INTEG_PEDIDO_REVERSO where NRO_PEDIDO = num_pedido;
  
  COMMIT;
  
END IF;

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    pedido_reverso := NULL;

END;