-- Este script ja é executado automaticamente toda vez que um teste de troca/devolução feito no selenium é executado, o script esta sendo salvo caso seja necessário executar o mesmo na mão

BEGIN
  /***********************************************************
   * CONFIGURAÇÃO DOS MOTIVOS DE UMA TROCA/DEVOLUÇAO
   ************************************************************/
   
  -- INSERT NA TABELA MV_TIPO_FLUXO_APROV_TROCADEV
  MERGE INTO MV_TIPO_FLUXO_APROV_TROCADEV
    USING DUAL ON (NRO_TIPO_FLUXO_APROV_TROCADEV = 1)
    WHEN NOT MATCHED THEN
      INSERT (NRO_TIPO_FLUXO_APROV_TROCADEV, DESC_TIPO_FLUXO_APROV, IND_ATIVO, NRO_USUARIO) VALUES ('1', 'TROCA', '1', 6699)
    WHEN MATCHED THEN
      UPDATE SET DESC_TIPO_FLUXO_APROV = 'TROCA', IND_ATIVO = '1', NRO_USUARIO = '6699';
    
  MERGE INTO MV_TIPO_FLUXO_APROV_TROCADEV
    USING DUAL ON (NRO_TIPO_FLUXO_APROV_TROCADEV = 2)
    WHEN NOT MATCHED THEN
      INSERT (NRO_TIPO_FLUXO_APROV_TROCADEV, DESC_TIPO_FLUXO_APROV, IND_ATIVO, NRO_USUARIO) VALUES ('2', 'DEVOLUÇÃO', '1', 6699)
    WHEN MATCHED THEN
      UPDATE SET DESC_TIPO_FLUXO_APROV = 'DEVOLUÇÃO', IND_ATIVO = '1', NRO_USUARIO = '6699';
    
  MERGE INTO MV_TIPO_FLUXO_APROV_TROCADEV
    USING DUAL ON (NRO_TIPO_FLUXO_APROV_TROCADEV = 3)
    WHEN NOT MATCHED THEN
      INSERT (NRO_TIPO_FLUXO_APROV_TROCADEV, DESC_TIPO_FLUXO_APROV, IND_ATIVO, NRO_USUARIO) VALUES ('3', 'AMBOS', '1', 6699)
    WHEN MATCHED THEN
      UPDATE SET DESC_TIPO_FLUXO_APROV = 'AMBOS', IND_ATIVO = '1', NRO_USUARIO = '6699';
   
   
  -- INSERT NA TABELA MV_MOTIVO_FLUXO_APROVACAO  
  MERGE INTO MV_MOTIVO_FLUXO_APROVACAO
    USING DUAL ON (NRO_MOTIVO_FLUXO_APROVACAO = 404)
    WHEN NOT MATCHED THEN
      INSERT (NRO_MOTIVO_FLUXO_APROVACAO, DESC_MOTIVO_FLUXO_APROVACAO, IND_ATIVO, NRO_USUARIO, NRO_EMPRESA, COD_MOTIVO) VALUES ('404', 'TESTE AUT. - ALERT_AUT_PDV_REC_DEV_PEND - TROCA', '1', '6699', '5', null)
    WHEN MATCHED THEN
      UPDATE SET  DESC_MOTIVO_FLUXO_APROVACAO = 'TESTE AUT. - ALERT_AUT_PDV_REC_DEV_PEND - TROCA', IND_ATIVO = '1', NRO_USUARIO = 6699, NRO_EMPRESA = '5', COD_MOTIVO = null;
    
  MERGE INTO MV_MOTIVO_FLUXO_APROVACAO
    USING DUAL ON (NRO_MOTIVO_FLUXO_APROVACAO = 405)
    WHEN NOT MATCHED THEN
      INSERT (NRO_MOTIVO_FLUXO_APROVACAO, DESC_MOTIVO_FLUXO_APROVACAO, IND_ATIVO, NRO_USUARIO, NRO_EMPRESA, COD_MOTIVO) VALUES ('405', 'TESTE AUT. - PER_GER_CON_FAT_DEV_APR - TROCA', '1', '6699', '5', null)
    WHEN MATCHED THEN
      UPDATE SET  DESC_MOTIVO_FLUXO_APROVACAO = 'TESTE AUT. - PER_GER_CON_FAT_DEV_APR - TROCA', IND_ATIVO = '1', NRO_USUARIO = 6699, NRO_EMPRESA = '5', COD_MOTIVO = null;
    
  MERGE INTO MV_MOTIVO_FLUXO_APROVACAO
    USING DUAL ON (NRO_MOTIVO_FLUXO_APROVACAO = 406)
    WHEN NOT MATCHED THEN
      INSERT (NRO_MOTIVO_FLUXO_APROVACAO, DESC_MOTIVO_FLUXO_APROVACAO, IND_ATIVO, NRO_USUARIO, NRO_EMPRESA, COD_MOTIVO) VALUES ('406', 'TESTE AUT. - EXIGE_APROVACAO_FINANCEIRO - DEVOL', '1', '6699', '5', null)
    WHEN MATCHED THEN
      UPDATE SET  DESC_MOTIVO_FLUXO_APROVACAO = 'TESTE AUT. - EXIGE_APROVACAO_FINANCEIRO - DEVOL', IND_ATIVO = '1', NRO_USUARIO = 6699, NRO_EMPRESA = '5', COD_MOTIVO = null;
    
  MERGE INTO MV_MOTIVO_FLUXO_APROVACAO
    USING DUAL ON (NRO_MOTIVO_FLUXO_APROVACAO = 407)
    WHEN NOT MATCHED THEN
      INSERT (NRO_MOTIVO_FLUXO_APROVACAO, DESC_MOTIVO_FLUXO_APROVACAO, IND_ATIVO, NRO_USUARIO, NRO_EMPRESA, COD_MOTIVO) VALUES ('407', 'TESTE AUT. - APROVA_REVERSAO_AUTOMATICO - DEVOL', '1', '6699', '5', null)
    WHEN MATCHED THEN
      UPDATE SET  DESC_MOTIVO_FLUXO_APROVACAO = 'TESTE AUT. - APROVA_REVERSAO_AUTOMATICO - DEVOL', IND_ATIVO = '1', NRO_USUARIO = 6699, NRO_EMPRESA = '5', COD_MOTIVO = null;
    
  MERGE INTO MV_MOTIVO_FLUXO_APROVACAO
    USING DUAL ON (NRO_MOTIVO_FLUXO_APROVACAO = 408)
    WHEN NOT MATCHED THEN
      INSERT (NRO_MOTIVO_FLUXO_APROVACAO, DESC_MOTIVO_FLUXO_APROVACAO, IND_ATIVO, NRO_USUARIO, NRO_EMPRESA, COD_MOTIVO) VALUES ('408', 'TESTE AUT. - MARCAR_CONTR_BAIXA_PRIO - DEVOL', '1', '6699', '5', null)
    WHEN MATCHED THEN
      UPDATE SET  DESC_MOTIVO_FLUXO_APROVACAO = 'TESTE AUT. - MARCAR_CONTR_BAIXA_PRIO - DEVOL', IND_ATIVO = '1', NRO_USUARIO = 6699, NRO_EMPRESA = '5', COD_MOTIVO = null;
    
  MERGE INTO MV_MOTIVO_FLUXO_APROVACAO
    USING DUAL ON (NRO_MOTIVO_FLUXO_APROVACAO = 409)
    WHEN NOT MATCHED THEN
      INSERT (NRO_MOTIVO_FLUXO_APROVACAO, DESC_MOTIVO_FLUXO_APROVACAO, IND_ATIVO, NRO_USUARIO, NRO_EMPRESA, COD_MOTIVO) VALUES ('409', 'TESTE AUT. - LIB_REC_DEV_S_NF_DEV_CONF - TROCA', '1', '6699', '5', null)
    WHEN MATCHED THEN
      UPDATE SET  DESC_MOTIVO_FLUXO_APROVACAO = 'TESTE AUT. - LIB_REC_DEV_S_NF_DEV_CONF - TROCA', IND_ATIVO = '1', NRO_USUARIO = 6699, NRO_EMPRESA = '5', COD_MOTIVO = null;
    
  MERGE INTO MV_MOTIVO_FLUXO_APROVACAO
    USING DUAL ON (NRO_MOTIVO_FLUXO_APROVACAO = 410)
    WHEN NOT MATCHED THEN
      INSERT (NRO_MOTIVO_FLUXO_APROVACAO, DESC_MOTIVO_FLUXO_APROVACAO, IND_ATIVO, NRO_USUARIO, NRO_EMPRESA, COD_MOTIVO) VALUES ('410', 'TESTE AUT. - TROCA_SOMENTE_FATURADO - TROCA', '1', '6699', '5', null)
    WHEN MATCHED THEN
      UPDATE SET  DESC_MOTIVO_FLUXO_APROVACAO = 'TESTE AUT. - TROCA_SOMENTE_FATURADO - TROCA', IND_ATIVO = '1', NRO_USUARIO = 6699, NRO_EMPRESA = '5', COD_MOTIVO = null;
    
  MERGE INTO MV_MOTIVO_FLUXO_APROVACAO
    USING DUAL ON (NRO_MOTIVO_FLUXO_APROVACAO = 411)
    WHEN NOT MATCHED THEN
      INSERT (NRO_MOTIVO_FLUXO_APROVACAO, DESC_MOTIVO_FLUXO_APROVACAO, IND_ATIVO, NRO_USUARIO, NRO_EMPRESA, COD_MOTIVO) VALUES ('411', 'TESTE AUT. - NAO_PERMITE_DEVOLUCAO - DEVOLUCAO', '1', '6699', '5', null)
    WHEN MATCHED THEN
      UPDATE SET  DESC_MOTIVO_FLUXO_APROVACAO = 'TESTE AUT. - NAO_PERMITE_DEVOLUCAO - DEVOLUCAO', IND_ATIVO = '1', NRO_USUARIO = 6699, NRO_EMPRESA = '5', COD_MOTIVO = null;

  MERGE INTO MV_MOTIVO_FLUXO_APROVACAO
    USING DUAL ON (NRO_MOTIVO_FLUXO_APROVACAO = 412)
    WHEN NOT MATCHED THEN
      INSERT (NRO_MOTIVO_FLUXO_APROVACAO, DESC_MOTIVO_FLUXO_APROVACAO, IND_ATIVO, NRO_USUARIO, NRO_EMPRESA, COD_MOTIVO) VALUES ('412', 'TESTE AUT. - APR_ATD_PROD_NAO_FATUR - TROCA', '1', '6699', '5', null)
    WHEN MATCHED THEN
      UPDATE SET  DESC_MOTIVO_FLUXO_APROVACAO = 'TESTE AUT. - APR_ATD_PROD_NAO_FATUR - TROCA', IND_ATIVO = '1', NRO_USUARIO = 6699, NRO_EMPRESA = '5', COD_MOTIVO = null;

	  
  -- INSERT NA TABELA MV_FLUXO_APROVACAO_TROCADEVOL
  MERGE INTO MV_FLUXO_APROVACAO_TROCADEVOL
    USING DUAL ON (NRO_FLUXO_APROVACAO_TROCADEVOL = 416)
    WHEN NOT MATCHED THEN
      INSERT (NRO_FLUXO_APROVACAO_TROCADEVOL, DESC_FLUXO_APROVACAO, IND_ATIVO, NRO_USUARIO, COD_PRIVILEGIO_ADM_APROVADOR, NRO_TIPO_FLUXO_APROV_TROCADEV) VALUES ('416', 'FLUXO - ALERT_AUT_PDV_REC_DEV_PEND', '1', '6699', 'LIBERATRODAPRODDEFEITO', '1')
    WHEN MATCHED THEN
      UPDATE SET DESC_FLUXO_APROVACAO = 'FLUXO - ALERT_AUT_PDV_REC_DEV_PEND', IND_ATIVO = '1', NRO_USUARIO = 6699, COD_PRIVILEGIO_ADM_APROVADOR = 'LIBERATRODAPRODDEFEITO', NRO_TIPO_FLUXO_APROV_TROCADEV = '1';
      
  MERGE INTO MV_FLUXO_APROVACAO_TROCADEVOL
    USING DUAL ON (NRO_FLUXO_APROVACAO_TROCADEVOL = 417)
    WHEN NOT MATCHED THEN
      INSERT (NRO_FLUXO_APROVACAO_TROCADEVOL, DESC_FLUXO_APROVACAO, IND_ATIVO, NRO_USUARIO, COD_PRIVILEGIO_ADM_APROVADOR, NRO_TIPO_FLUXO_APROV_TROCADEV) VALUES ('417', 'FLUXO - PER_GER_CON_FAT_DEV_APR', '1', '6699', 'LIBERATRODAPRODDEFEITO', '1')
    WHEN MATCHED THEN
      UPDATE SET DESC_FLUXO_APROVACAO = 'FLUXO - PER_GER_CON_FAT_DEV_APR', IND_ATIVO = '1', NRO_USUARIO = 6699, COD_PRIVILEGIO_ADM_APROVADOR = 'LIBERATRODAPRODDEFEITO', NRO_TIPO_FLUXO_APROV_TROCADEV = '1';
      
  MERGE INTO MV_FLUXO_APROVACAO_TROCADEVOL
    USING DUAL ON (NRO_FLUXO_APROVACAO_TROCADEVOL = 418)
    WHEN NOT MATCHED THEN
      INSERT (NRO_FLUXO_APROVACAO_TROCADEVOL, DESC_FLUXO_APROVACAO, IND_ATIVO, NRO_USUARIO, COD_PRIVILEGIO_ADM_APROVADOR, NRO_TIPO_FLUXO_APROV_TROCADEV) VALUES ('418', 'FLUXO - EXIGE_APROVACAO_FINANCEIRO', '1', '6699', 'LIBERATRODAPRODDEFEITO', '2')
    WHEN MATCHED THEN
      UPDATE SET DESC_FLUXO_APROVACAO = 'FLUXO - EXIGE_APROVACAO_FINANCEIRO', IND_ATIVO = '1', NRO_USUARIO = 6699, COD_PRIVILEGIO_ADM_APROVADOR = 'LIBERATRODAPRODDEFEITO', NRO_TIPO_FLUXO_APROV_TROCADEV = '2';

  MERGE INTO MV_FLUXO_APROVACAO_TROCADEVOL
    USING DUAL ON (NRO_FLUXO_APROVACAO_TROCADEVOL = 419)
    WHEN NOT MATCHED THEN
      INSERT (NRO_FLUXO_APROVACAO_TROCADEVOL, DESC_FLUXO_APROVACAO, IND_ATIVO, NRO_USUARIO, COD_PRIVILEGIO_ADM_APROVADOR, NRO_TIPO_FLUXO_APROV_TROCADEV) VALUES ('419', 'FLUXO - APROVA_REVERSAO_AUTOMATICO', '1', '6699', 'LIBERATRODAPRODDEFEITO', '2')
    WHEN MATCHED THEN
      UPDATE SET DESC_FLUXO_APROVACAO = 'FLUXO - APROVA_REVERSAO_AUTOMATICO', IND_ATIVO = '1', NRO_USUARIO = 6699, COD_PRIVILEGIO_ADM_APROVADOR = 'LIBERATRODAPRODDEFEITO', NRO_TIPO_FLUXO_APROV_TROCADEV = '2';

  MERGE INTO MV_FLUXO_APROVACAO_TROCADEVOL
    USING DUAL ON (NRO_FLUXO_APROVACAO_TROCADEVOL = 420)
    WHEN NOT MATCHED THEN
      INSERT (NRO_FLUXO_APROVACAO_TROCADEVOL, DESC_FLUXO_APROVACAO, IND_ATIVO, NRO_USUARIO, COD_PRIVILEGIO_ADM_APROVADOR, NRO_TIPO_FLUXO_APROV_TROCADEV) VALUES ('420', 'FLUXO - MARCAR_CONTR_BAIXA_PRIO', '1', '6699', 'LIBERATRODAPRODDEFEITO', '2')
    WHEN MATCHED THEN
      UPDATE SET DESC_FLUXO_APROVACAO = 'FLUXO - MARCAR_CONTR_BAIXA_PRIO', IND_ATIVO = '1', NRO_USUARIO = 6699, COD_PRIVILEGIO_ADM_APROVADOR = 'LIBERATRODAPRODDEFEITO', NRO_TIPO_FLUXO_APROV_TROCADEV = '2';
    
  MERGE INTO MV_FLUXO_APROVACAO_TROCADEVOL
    USING DUAL ON (NRO_FLUXO_APROVACAO_TROCADEVOL = 421)
    WHEN NOT MATCHED THEN
      INSERT (NRO_FLUXO_APROVACAO_TROCADEVOL, DESC_FLUXO_APROVACAO, IND_ATIVO, NRO_USUARIO, COD_PRIVILEGIO_ADM_APROVADOR, NRO_TIPO_FLUXO_APROV_TROCADEV) VALUES ('421', 'FLUXO - LIB_REC_DEV_S_NF_DEV_CONF', '1', '6699', 'LIBERATRODAPRODDEFEITO', '1')
    WHEN MATCHED THEN
      UPDATE SET DESC_FLUXO_APROVACAO = 'FLUXO - LIB_REC_DEV_S_NF_DEV_CONF', IND_ATIVO = '1', NRO_USUARIO = 6699, COD_PRIVILEGIO_ADM_APROVADOR = 'LIBERATRODAPRODDEFEITO', NRO_TIPO_FLUXO_APROV_TROCADEV = '1';

  MERGE INTO MV_FLUXO_APROVACAO_TROCADEVOL
    USING DUAL ON (NRO_FLUXO_APROVACAO_TROCADEVOL = 422)
    WHEN NOT MATCHED THEN
      INSERT (NRO_FLUXO_APROVACAO_TROCADEVOL, DESC_FLUXO_APROVACAO, IND_ATIVO, NRO_USUARIO, COD_PRIVILEGIO_ADM_APROVADOR, NRO_TIPO_FLUXO_APROV_TROCADEV) VALUES ('422', 'FLUXO - TROCA_SOMENTE_FATURADO', '1', '6699', 'LIBERATRODAPRODDEFEITO', '1')
    WHEN MATCHED THEN
      UPDATE SET DESC_FLUXO_APROVACAO = 'FLUXO - TROCA_SOMENTE_FATURADO', IND_ATIVO = '1', NRO_USUARIO = 6699, COD_PRIVILEGIO_ADM_APROVADOR = 'LIBERATRODAPRODDEFEITO', NRO_TIPO_FLUXO_APROV_TROCADEV = '1';
  
  MERGE INTO MV_FLUXO_APROVACAO_TROCADEVOL
    USING DUAL ON (NRO_FLUXO_APROVACAO_TROCADEVOL = 423)
    WHEN NOT MATCHED THEN
      INSERT (NRO_FLUXO_APROVACAO_TROCADEVOL, DESC_FLUXO_APROVACAO, IND_ATIVO, NRO_USUARIO, COD_PRIVILEGIO_ADM_APROVADOR, NRO_TIPO_FLUXO_APROV_TROCADEV) VALUES ('423', 'FLUXO - NAO_PERMITE_DEVOLUCAO', '1', '6699', 'LIBERATRODAPRODDEFEITO', '2')
    WHEN MATCHED THEN
      UPDATE SET DESC_FLUXO_APROVACAO = 'FLUXO - NAO_PERMITE_DEVOLUCAO', IND_ATIVO = '1', NRO_USUARIO = 6699, COD_PRIVILEGIO_ADM_APROVADOR = 'LIBERATRODAPRODDEFEITO', NRO_TIPO_FLUXO_APROV_TROCADEV = '2';
    
  MERGE INTO MV_FLUXO_APROVACAO_TROCADEVOL
    USING DUAL ON (NRO_FLUXO_APROVACAO_TROCADEVOL = 424)
    WHEN NOT MATCHED THEN
      INSERT (NRO_FLUXO_APROVACAO_TROCADEVOL, DESC_FLUXO_APROVACAO, IND_ATIVO, NRO_USUARIO, COD_PRIVILEGIO_ADM_APROVADOR, NRO_TIPO_FLUXO_APROV_TROCADEV) VALUES ('424', 'FLUXO - APR_ATD_PROD_NAO_FATUR', '1', '6699', 'LIBERATRODAPRODDEFEITO', '1')
    WHEN MATCHED THEN
      UPDATE SET DESC_FLUXO_APROVACAO = 'FLUXO - APR_ATD_PROD_NAO_FATUR', IND_ATIVO = '1', NRO_USUARIO = 6699, COD_PRIVILEGIO_ADM_APROVADOR = 'LIBERATRODAPRODDEFEITO', NRO_TIPO_FLUXO_APROV_TROCADEV = '1';
	
	
  -- INSERT NA TABELA MV_ITEM_FLUXO_APROVACAO
  MERGE INTO MV_ITEM_FLUXO_APROVACAO
    USING DUAL ON (NRO_FLUXO_APROVACAO_TROCADEVOL = '416' AND NRO_SEQ_FASE = '1')
    WHEN NOT MATCHED THEN
      INSERT (NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_SEQ_FASE, DESC_FASE_APROVACAO, COD_PRIVILEGIO, NRO_USUARIO_ALTERACAO, DT_INCLUSAO, DT_ALTERACAO) VALUES ('416', '1', 'REGRA - ALERT_AUT_PDV_REC_DEV_PEND', 'LIBERATRODAPRODDEFEITO', '6699', '01/08/2016', '01/08/2016')
    WHEN MATCHED THEN
      UPDATE SET DESC_FASE_APROVACAO = 'REGRA - ALERT_AUT_PDV_REC_DEV_PEND', COD_PRIVILEGIO = 'LIBERATRODAPRODDEFEITO', NRO_USUARIO_ALTERACAO = '6699', DT_INCLUSAO = '01/08/2016', DT_ALTERACAO = '01/08/2016';
	
  MERGE INTO MV_ITEM_FLUXO_APROVACAO
    USING DUAL ON (NRO_FLUXO_APROVACAO_TROCADEVOL = '417' AND NRO_SEQ_FASE = '1')
    WHEN NOT MATCHED THEN
      INSERT (NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_SEQ_FASE, DESC_FASE_APROVACAO, COD_PRIVILEGIO, NRO_USUARIO_ALTERACAO, DT_INCLUSAO, DT_ALTERACAO) VALUES ('417', '1', 'REGRA - PER_GER_CON_FAT_DEV_APR', 'LIBERATRODAPRODDEFEITO', '6699', '01/08/2016', '01/08/2016')
    WHEN MATCHED THEN
      UPDATE SET DESC_FASE_APROVACAO = 'REGRA - PER_GER_CON_FAT_DEV_APR', COD_PRIVILEGIO = 'LIBERATRODAPRODDEFEITO', NRO_USUARIO_ALTERACAO = '6699', DT_INCLUSAO = '01/08/2016', DT_ALTERACAO = '01/08/2016';

  MERGE INTO MV_ITEM_FLUXO_APROVACAO
    USING DUAL ON (NRO_FLUXO_APROVACAO_TROCADEVOL = '418' AND NRO_SEQ_FASE = '1')
    WHEN NOT MATCHED THEN
      INSERT (NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_SEQ_FASE, DESC_FASE_APROVACAO, COD_PRIVILEGIO, NRO_USUARIO_ALTERACAO, DT_INCLUSAO, DT_ALTERACAO) VALUES ('418', '1', 'REGRA - EXIGE_APROVACAO_FINANCEIRO', 'LIBERATRODAPRODDEFEITO', '6699', '01/08/2016', '01/08/2016')
    WHEN MATCHED THEN
      UPDATE SET DESC_FASE_APROVACAO = 'REGRA - EXIGE_APROVACAO_FINANCEIRO', COD_PRIVILEGIO = 'LIBERATRODAPRODDEFEITO', NRO_USUARIO_ALTERACAO = '6699', DT_INCLUSAO = '01/08/2016', DT_ALTERACAO = '01/08/2016';

  MERGE INTO MV_ITEM_FLUXO_APROVACAO
    USING DUAL ON (NRO_FLUXO_APROVACAO_TROCADEVOL = '419' AND NRO_SEQ_FASE = '1')
    WHEN NOT MATCHED THEN
      INSERT (NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_SEQ_FASE, DESC_FASE_APROVACAO, COD_PRIVILEGIO, NRO_USUARIO_ALTERACAO, DT_INCLUSAO, DT_ALTERACAO) VALUES ('419', '1', 'REGRA - APROVA_REVERSAO_AUTOMATICO', 'LIBERATRODAPRODDEFEITO', '6699', '01/08/2016', '01/08/2016')
    WHEN MATCHED THEN
      UPDATE SET DESC_FASE_APROVACAO = 'REGRA - APROVA_REVERSAO_AUTOMATICO', COD_PRIVILEGIO = 'LIBERATRODAPRODDEFEITO', NRO_USUARIO_ALTERACAO = '6699', DT_INCLUSAO = '01/08/2016', DT_ALTERACAO = '01/08/2016';
	  
  MERGE INTO MV_ITEM_FLUXO_APROVACAO
    USING DUAL ON (NRO_FLUXO_APROVACAO_TROCADEVOL = '420' AND NRO_SEQ_FASE = '1')
    WHEN NOT MATCHED THEN
      INSERT (NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_SEQ_FASE, DESC_FASE_APROVACAO, COD_PRIVILEGIO, NRO_USUARIO_ALTERACAO, DT_INCLUSAO, DT_ALTERACAO) VALUES ('420', '1', 'REGRA - MARCAR_CONTR_BAIXA_PRIO', 'LIBERATRODAPRODDEFEITO', '6699', '01/08/2016', '01/08/2016')
    WHEN MATCHED THEN
      UPDATE SET DESC_FASE_APROVACAO = 'REGRA - MARCAR_CONTR_BAIXA_PRIO', COD_PRIVILEGIO = 'LIBERATRODAPRODDEFEITO', NRO_USUARIO_ALTERACAO = '6699', DT_INCLUSAO = '01/08/2016', DT_ALTERACAO = '01/08/2016';

  MERGE INTO MV_ITEM_FLUXO_APROVACAO
    USING DUAL ON (NRO_FLUXO_APROVACAO_TROCADEVOL = '421' AND NRO_SEQ_FASE = '1')
    WHEN NOT MATCHED THEN
      INSERT (NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_SEQ_FASE, DESC_FASE_APROVACAO, COD_PRIVILEGIO, NRO_USUARIO_ALTERACAO, DT_INCLUSAO, DT_ALTERACAO) VALUES ('421', '1', 'REGRA - LIB_REC_DEV_S_NF_DEV_CONF', 'LIBERATRODAPRODDEFEITO', '6699', '01/08/2016', '01/08/2016')
    WHEN MATCHED THEN
      UPDATE SET DESC_FASE_APROVACAO = 'REGRA - LIB_REC_DEV_S_NF_DEV_CONF', COD_PRIVILEGIO = 'LIBERATRODAPRODDEFEITO', NRO_USUARIO_ALTERACAO = '6699', DT_INCLUSAO = '01/08/2016', DT_ALTERACAO = '01/08/2016';
	  
  MERGE INTO MV_ITEM_FLUXO_APROVACAO
    USING DUAL ON (NRO_FLUXO_APROVACAO_TROCADEVOL = '422' AND NRO_SEQ_FASE = '1')
    WHEN NOT MATCHED THEN
      INSERT (NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_SEQ_FASE, DESC_FASE_APROVACAO, COD_PRIVILEGIO, NRO_USUARIO_ALTERACAO, DT_INCLUSAO, DT_ALTERACAO) VALUES ('422', '1', 'REGRA - TROCA_SOMENTE_FATURADO', 'LIBERATRODAPRODDEFEITO', '6699', '01/08/2016', '01/08/2016')
    WHEN MATCHED THEN
      UPDATE SET DESC_FASE_APROVACAO = 'REGRA - TROCA_SOMENTE_FATURADO', COD_PRIVILEGIO = 'LIBERATRODAPRODDEFEITO', NRO_USUARIO_ALTERACAO = '6699', DT_INCLUSAO = '01/08/2016', DT_ALTERACAO = '01/08/2016';
	  
  MERGE INTO MV_ITEM_FLUXO_APROVACAO
    USING DUAL ON (NRO_FLUXO_APROVACAO_TROCADEVOL = '423' AND NRO_SEQ_FASE = '1')
    WHEN NOT MATCHED THEN
      INSERT (NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_SEQ_FASE, DESC_FASE_APROVACAO, COD_PRIVILEGIO, NRO_USUARIO_ALTERACAO, DT_INCLUSAO, DT_ALTERACAO) VALUES ('423', '1', 'REGRA - NAO_PERMITE_DEVOLUCAO', 'LIBERATRODAPRODDEFEITO', '6699', '01/08/2016', '01/08/2016')
    WHEN MATCHED THEN
      UPDATE SET DESC_FASE_APROVACAO = 'REGRA - NAO_PERMITE_DEVOLUCAO', COD_PRIVILEGIO = 'LIBERATRODAPRODDEFEITO', NRO_USUARIO_ALTERACAO = '6699', DT_INCLUSAO = '01/08/2016', DT_ALTERACAO = '01/08/2016';
	  
  MERGE INTO MV_ITEM_FLUXO_APROVACAO
    USING DUAL ON (NRO_FLUXO_APROVACAO_TROCADEVOL = '424' AND NRO_SEQ_FASE = '1')
    WHEN NOT MATCHED THEN
      INSERT (NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_SEQ_FASE, DESC_FASE_APROVACAO, COD_PRIVILEGIO, NRO_USUARIO_ALTERACAO, DT_INCLUSAO, DT_ALTERACAO) VALUES ('424', '1', 'REGRA - FLUXO - APR_ATD_PROD_NAO_FATUR', 'LIBERATRODAPRODDEFEITO', '6699', '01/08/2016', '01/08/2016')
    WHEN MATCHED THEN
      UPDATE SET DESC_FASE_APROVACAO = 'REGRA - APR_ATD_PROD_NAO_FATUR', COD_PRIVILEGIO = 'LIBERATRODAPRODDEFEITO', NRO_USUARIO_ALTERACAO = '6699', DT_INCLUSAO = '01/08/2016', DT_ALTERACAO = '01/08/2016';
	 
		
  -- INSERT NA TABELA MV_REGRA_X_ITEMFLUXOAPROVACAO
  MERGE INTO MV_REGRA_X_ITEMFLUXOAPROVACAO
    USING DUAL ON (NRO_SEQ_REGRA = '4' AND NRO_FLUXO_APROVACAO_TROCADEVOL = '416' AND NRO_SEQ_FASE = '1')
    WHEN NOT MATCHED THEN
      INSERT (NRO_SEQ_REGRA, NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_SEQ_FASE, NRO_USUARIO_ALTERACAO) VALUES ('4', '416', '1', '6699')
    WHEN MATCHED THEN
      UPDATE SET NRO_USUARIO_ALTERACAO = '6699';
	  
  MERGE INTO MV_REGRA_X_ITEMFLUXOAPROVACAO
    USING DUAL ON (NRO_SEQ_REGRA = '1' AND NRO_FLUXO_APROVACAO_TROCADEVOL = '417' AND NRO_SEQ_FASE = '1')
    WHEN NOT MATCHED THEN
      INSERT (NRO_SEQ_REGRA, NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_SEQ_FASE, NRO_USUARIO_ALTERACAO) VALUES ('1', '417', '1', '6699')
    WHEN MATCHED THEN
      UPDATE SET NRO_USUARIO_ALTERACAO = '6699'; 
	  
  MERGE INTO MV_REGRA_X_ITEMFLUXOAPROVACAO
    USING DUAL ON (NRO_SEQ_REGRA = '5' AND NRO_FLUXO_APROVACAO_TROCADEVOL = '418' AND NRO_SEQ_FASE = '1')
    WHEN NOT MATCHED THEN
      INSERT (NRO_SEQ_REGRA, NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_SEQ_FASE, NRO_USUARIO_ALTERACAO) VALUES ('5', '418', '1', '6699')
    WHEN MATCHED THEN
      UPDATE SET NRO_USUARIO_ALTERACAO = '6699'; 

  MERGE INTO MV_REGRA_X_ITEMFLUXOAPROVACAO
    USING DUAL ON (NRO_SEQ_REGRA = '6' AND NRO_FLUXO_APROVACAO_TROCADEVOL = '419' AND NRO_SEQ_FASE = '1')
    WHEN NOT MATCHED THEN
      INSERT (NRO_SEQ_REGRA, NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_SEQ_FASE, NRO_USUARIO_ALTERACAO) VALUES ('6', '419', '1', '6699')
    WHEN MATCHED THEN
      UPDATE SET NRO_USUARIO_ALTERACAO = '6699'; 

  MERGE INTO MV_REGRA_X_ITEMFLUXOAPROVACAO
    USING DUAL ON (NRO_SEQ_REGRA = '3' AND NRO_FLUXO_APROVACAO_TROCADEVOL = '420' AND NRO_SEQ_FASE = '1')
    WHEN NOT MATCHED THEN
      INSERT (NRO_SEQ_REGRA, NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_SEQ_FASE, NRO_USUARIO_ALTERACAO) VALUES ('3', '420', '1', '6699')
    WHEN MATCHED THEN
      UPDATE SET NRO_USUARIO_ALTERACAO = '6699'; 
	  
  MERGE INTO MV_REGRA_X_ITEMFLUXOAPROVACAO
    USING DUAL ON (NRO_SEQ_REGRA = '2' AND NRO_FLUXO_APROVACAO_TROCADEVOL = '421' AND NRO_SEQ_FASE = '1')
    WHEN NOT MATCHED THEN
      INSERT (NRO_SEQ_REGRA, NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_SEQ_FASE, NRO_USUARIO_ALTERACAO) VALUES ('2', '421', '1', '6699')
    WHEN MATCHED THEN
      UPDATE SET NRO_USUARIO_ALTERACAO = '6699'; 
	  
  MERGE INTO MV_REGRA_X_ITEMFLUXOAPROVACAO
    USING DUAL ON (NRO_SEQ_REGRA = '7' AND NRO_FLUXO_APROVACAO_TROCADEVOL = '422' AND NRO_SEQ_FASE = '1')
    WHEN NOT MATCHED THEN
      INSERT (NRO_SEQ_REGRA, NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_SEQ_FASE, NRO_USUARIO_ALTERACAO) VALUES ('7', '422', '1', '6699')
    WHEN MATCHED THEN
      UPDATE SET NRO_USUARIO_ALTERACAO = '6699'; 
	  
  MERGE INTO MV_REGRA_X_ITEMFLUXOAPROVACAO
    USING DUAL ON (NRO_SEQ_REGRA = '8' AND NRO_FLUXO_APROVACAO_TROCADEVOL = '423' AND NRO_SEQ_FASE = '1')
    WHEN NOT MATCHED THEN
      INSERT (NRO_SEQ_REGRA, NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_SEQ_FASE, NRO_USUARIO_ALTERACAO) VALUES ('8', '423', '1', '6699')
    WHEN MATCHED THEN
      UPDATE SET NRO_USUARIO_ALTERACAO = '6699'; 
	  
  MERGE INTO MV_REGRA_X_ITEMFLUXOAPROVACAO
    USING DUAL ON (NRO_SEQ_REGRA = '9' AND NRO_FLUXO_APROVACAO_TROCADEVOL = '424' AND NRO_SEQ_FASE = '1')
    WHEN NOT MATCHED THEN
      INSERT (NRO_SEQ_REGRA, NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_SEQ_FASE, NRO_USUARIO_ALTERACAO) VALUES ('9', '424', '1', '6699')
    WHEN MATCHED THEN
      UPDATE SET NRO_USUARIO_ALTERACAO = '6699'; 

	  
  -- INSERT NA TABELA MV_CONFIG_APROVACAO_TROCADEVOL
  MERGE INTO MV_CONFIG_APROVACAO_TROCADEVOL
    USING DUAL ON (NRO_CONFIG_APROVACAO = 622503)
    WHEN NOT MATCHED THEN
      INSERT (NRO_CONFIG_APROVACAO, NRO_SUBGRUPO_PRODUTO, NRO_GRUPO_PRODUTO, NRO_DEPTO, NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_LOJA, NRO_USUARIO, NRO_MOTIVO_FLUXO_APROVACAO) VALUES ('622503', null, null, '26', '416', '1101', '6699', '404')
    WHEN MATCHED THEN
      UPDATE SET NRO_SUBGRUPO_PRODUTO = null, NRO_GRUPO_PRODUTO = null, NRO_DEPTO = '26', NRO_FLUXO_APROVACAO_TROCADEVOL = '416', NRO_LOJA = '1101', NRO_USUARIO = '6699', NRO_MOTIVO_FLUXO_APROVACAO = '404';
      
  MERGE INTO MV_CONFIG_APROVACAO_TROCADEVOL
    USING DUAL ON (NRO_CONFIG_APROVACAO = 622504)
    WHEN NOT MATCHED THEN
      INSERT (NRO_CONFIG_APROVACAO, NRO_SUBGRUPO_PRODUTO, NRO_GRUPO_PRODUTO, NRO_DEPTO, NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_LOJA, NRO_USUARIO, NRO_MOTIVO_FLUXO_APROVACAO) VALUES ('622504', null, null, '26', '417', '1101', '6699', '405')
    WHEN MATCHED THEN
      UPDATE SET NRO_SUBGRUPO_PRODUTO = null, NRO_GRUPO_PRODUTO = null, NRO_DEPTO = '26', NRO_FLUXO_APROVACAO_TROCADEVOL = '417', NRO_LOJA = '1101', NRO_USUARIO = '6699', NRO_MOTIVO_FLUXO_APROVACAO = '405';
    
  MERGE INTO MV_CONFIG_APROVACAO_TROCADEVOL
    USING DUAL ON (NRO_CONFIG_APROVACAO = 622505)
    WHEN NOT MATCHED THEN
      INSERT (NRO_CONFIG_APROVACAO, NRO_SUBGRUPO_PRODUTO, NRO_GRUPO_PRODUTO, NRO_DEPTO, NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_LOJA, NRO_USUARIO, NRO_MOTIVO_FLUXO_APROVACAO) VALUES ('622505', null, null, '26', '418', '1101', '6699', '406')
    WHEN MATCHED THEN
      UPDATE SET NRO_SUBGRUPO_PRODUTO = null, NRO_GRUPO_PRODUTO = null, NRO_DEPTO = '26', NRO_FLUXO_APROVACAO_TROCADEVOL = '418', NRO_LOJA = '1101', NRO_USUARIO = '6699', NRO_MOTIVO_FLUXO_APROVACAO = '406';
    
  MERGE INTO MV_CONFIG_APROVACAO_TROCADEVOL
    USING DUAL ON (NRO_CONFIG_APROVACAO = 622506)
    WHEN NOT MATCHED THEN
      INSERT (NRO_CONFIG_APROVACAO, NRO_SUBGRUPO_PRODUTO, NRO_GRUPO_PRODUTO, NRO_DEPTO, NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_LOJA, NRO_USUARIO, NRO_MOTIVO_FLUXO_APROVACAO) VALUES ('622506', null, null, '26', '419', '1101', '6699', '407')
    WHEN MATCHED THEN
      UPDATE SET NRO_SUBGRUPO_PRODUTO = null, NRO_GRUPO_PRODUTO = null, NRO_DEPTO = '26', NRO_FLUXO_APROVACAO_TROCADEVOL = '419', NRO_LOJA = '1101', NRO_USUARIO = '6699', NRO_MOTIVO_FLUXO_APROVACAO = '407';
    
  MERGE INTO MV_CONFIG_APROVACAO_TROCADEVOL
    USING DUAL ON (NRO_CONFIG_APROVACAO = 622507)
    WHEN NOT MATCHED THEN
      INSERT (NRO_CONFIG_APROVACAO, NRO_SUBGRUPO_PRODUTO, NRO_GRUPO_PRODUTO, NRO_DEPTO, NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_LOJA, NRO_USUARIO, NRO_MOTIVO_FLUXO_APROVACAO) VALUES ('622507', null, null, '26', '420', '1101', '6699', '408')
    WHEN MATCHED THEN
      UPDATE SET NRO_SUBGRUPO_PRODUTO = null, NRO_GRUPO_PRODUTO = null, NRO_DEPTO = '26', NRO_FLUXO_APROVACAO_TROCADEVOL = '420', NRO_LOJA = '1101', NRO_USUARIO = '6699', NRO_MOTIVO_FLUXO_APROVACAO = '408';
      
  MERGE INTO MV_CONFIG_APROVACAO_TROCADEVOL
    USING DUAL ON (NRO_CONFIG_APROVACAO = 622508)
    WHEN NOT MATCHED THEN
      INSERT (NRO_CONFIG_APROVACAO, NRO_SUBGRUPO_PRODUTO, NRO_GRUPO_PRODUTO, NRO_DEPTO, NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_LOJA, NRO_USUARIO, NRO_MOTIVO_FLUXO_APROVACAO) VALUES ('622508', null, null, '26', '421', '1101', '6699', '409')
    WHEN MATCHED THEN
      UPDATE SET NRO_SUBGRUPO_PRODUTO = null, NRO_GRUPO_PRODUTO = null, NRO_DEPTO = '26', NRO_FLUXO_APROVACAO_TROCADEVOL = '421', NRO_LOJA = '1101', NRO_USUARIO = '6699', NRO_MOTIVO_FLUXO_APROVACAO = '409';
    
  MERGE INTO MV_CONFIG_APROVACAO_TROCADEVOL
    USING DUAL ON (NRO_CONFIG_APROVACAO = 622509)
    WHEN NOT MATCHED THEN
      INSERT (NRO_CONFIG_APROVACAO, NRO_SUBGRUPO_PRODUTO, NRO_GRUPO_PRODUTO, NRO_DEPTO, NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_LOJA, NRO_USUARIO, NRO_MOTIVO_FLUXO_APROVACAO) VALUES ('622509', null, null, '26', '422', '1101', '6699', '410')
    WHEN MATCHED THEN
      UPDATE SET NRO_SUBGRUPO_PRODUTO = null, NRO_GRUPO_PRODUTO = null, NRO_DEPTO = '26', NRO_FLUXO_APROVACAO_TROCADEVOL = '422', NRO_LOJA = '1101', NRO_USUARIO = '6699', NRO_MOTIVO_FLUXO_APROVACAO = '410';
      
  MERGE INTO MV_CONFIG_APROVACAO_TROCADEVOL
    USING DUAL ON (NRO_CONFIG_APROVACAO = 622510)
    WHEN NOT MATCHED THEN
      INSERT (NRO_CONFIG_APROVACAO, NRO_SUBGRUPO_PRODUTO, NRO_GRUPO_PRODUTO, NRO_DEPTO, NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_LOJA, NRO_USUARIO, NRO_MOTIVO_FLUXO_APROVACAO) VALUES ('622510', null, null, '26', '423', '1101', '6699', '411')
    WHEN MATCHED THEN
      UPDATE SET NRO_SUBGRUPO_PRODUTO = null, NRO_GRUPO_PRODUTO = null, NRO_DEPTO = '26', NRO_FLUXO_APROVACAO_TROCADEVOL = '423', NRO_LOJA = '1101', NRO_USUARIO = '6699', NRO_MOTIVO_FLUXO_APROVACAO = '411';

  MERGE INTO MV_CONFIG_APROVACAO_TROCADEVOL
    USING DUAL ON (NRO_CONFIG_APROVACAO = 622511)
    WHEN NOT MATCHED THEN
      INSERT (NRO_CONFIG_APROVACAO, NRO_SUBGRUPO_PRODUTO, NRO_GRUPO_PRODUTO, NRO_DEPTO, NRO_FLUXO_APROVACAO_TROCADEVOL, NRO_LOJA, NRO_USUARIO, NRO_MOTIVO_FLUXO_APROVACAO) VALUES ('622511', null, null, '26', '424', '1101', '6699', '412')
    WHEN MATCHED THEN
      UPDATE SET NRO_SUBGRUPO_PRODUTO = null, NRO_GRUPO_PRODUTO = null, NRO_DEPTO = '26', NRO_FLUXO_APROVACAO_TROCADEVOL = '424', NRO_LOJA = '1101', NRO_USUARIO = '6699', NRO_MOTIVO_FLUXO_APROVACAO = '412';

END;