package br.com.mv.model;

public enum SessionVariables {
    NRO_PEDIDO,
    NRO_PRE_RECIBO,
    NRO_LOJA,
    COD_NRO_LOJA,
    NRO_NF_AVULSA,
    NRO_USUARIO,
    NRO_CARGA_VEICULO,
    VAL_UNITARIO_PRODUTO,
    NRO_NOTA_FISCAL,
    NRO_CUPOM_FISCAL,
    NRO_BORDERO,
    VLR_PEDIDO_TROCA_COM_REVERSAO,
    VLR_PEDIDO_TROCA_SEM_REVERSAO,
    NRO_IMPORTACAO_PROMOCAO,
    PERIODO_DATA_ABERTURA,
    PERIODO_DATA_FECHAMENTO
}
