DECLARE
  
BEGIN
	
	MERGE INTO MV_USUARIO_X_PRIVILEGIO
    USING DUAL ON (NRO_USUARIO = 6699 AND COD_PRIVILEGIO = 'LIBERARPEDIDOSEMATIVACAO')
    WHEN NOT MATCHED THEN
      Insert (NRO_USUARIO,COD_PRIVILEGIO,NRO_USUARIO_ALTERACAO,DT_INCLUSAO,DT_ALTERACAO,CAMPO_PRIVILEGIO_N1,CAMPO_PRIVILEGIO_N2,CAMPO_PRIVILEGIO_N3) values ('6699','LIBERARPEDIDOSEMATIVACAO','7380',to_date('19/04/18','DD/MM/RR'),to_date('19/04/18','DD/MM/RR'),null,null,null);
      
END;